name: Dev Branch CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to fetch all history for diff

      # 2️⃣ Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4️⃣ Lint with flake8
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 5️⃣ Run tests
      - name: Run tests with pytest
        run: |
          pytest

      # 6️⃣ Auto PR to main
      - name: Create Pull Request to main
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}   # Built-in token is enough
          commit-message: "Auto PR: dev → main"
          title: "Merge dev into main"
          body: "Automated PR created after successful dev workflow"
          base: main
          branch: dev
          create-branch: false
          labels: "auto-pr"